AWSTemplateFormatVersion: '2010-09-09'
Description: DataSentinel VPC

Parameters:
  Environment:
    Type: String

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub 'datasentinel-vpc-${Environment}'

Outputs:
  VpcId:
    Value: !Ref VPC
    Export:
      Name: !Sub 'datasentinel-foundation-${Environment}-VpcId'
